module-name: kyma-companion
rc-tag: 1.0.1
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/kyma-companion:1.0.1
whitesource:
  language: python
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test"
