name: "test wait"

on:
  push:
    branches:
      - main

jobs:
  wait-for-build-job:
    name: Wait for prow jobs
    needs: [ create-draft, bump-sec-scanners-config ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout eventing-tools
        uses: actions/checkout@v4
        with:
          repository: 'kyma-project/eventing-tools'
          path: 'kyma-project/eventing-tools'
          ref: main
          sparse-checkout: 'scripts/wait-for-commit-check'

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install requirements
        run: |
          pip install -r $GITHUB_WORKSPACE/kyma-project/eventing-tools/scripts/wait-for-commit-check/requirements.txt

      - name: wait for build
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY_FULL_NAME: "kyma-project/eventing-auth-manager"
          GIT_REF: "29e353eb9d446fbe5eb727e08de711ec2a8b1ae7"
          GIT_CHECK_RUN_NAME: "build / Build image"
          INTERVAL: 60
          TIMEOUT: 900
        run: |
          python $GITHUB_WORKSPACE/scripts/wait-for-commit-check/run.py

      - name: Check if release-eventing-auth-manager-build status is not success
        if: steps.wait-for-post-eam-release-build.outputs.state != 'success'
        run: |
          echo 'release-eventing-auth-manager-build failed.'
          exit 1
